### ISSUE TITLE
Watch file changes, for automatic file reloading

### ISSUE THREAD

**Issue by gevorg** [http-auth/http-auth#60]
We need some mechanism to reload htpasswd/htdigest files if there were changed during application run.

**Comment by gevorg** [comment]
Better let's restart server as file is changed..

**Comment by sisou** [comment]
I just ran into this today, as I implement a administration interface to update the users and passwords, by manipulating the htpasswd file.

I understand it's better/easier to restart the server, but my application needs to run in a continuous, reliable, persistant fashion.

Can you think of any way to force reloading the file without restarting the server?

**Comment by gevorg** [comment]
I see two options here:

 - Use custom authentication and write your logic there
 - Or/And write your own /src/auth/base.js and add reloading logic there

**Comment by sisou** [comment]
I was able to trigger a manual htpasswd file reloading by simply issuing:

```javascript
// Standard setup
var usersauth = httpauth.basic({realm: 'Users', file: path.join(config_dir, 'users.htpasswd')});
app.use(httpauth.connect(usersauth));

// ...

// This clears the loaded userlist and reloads the file
usersauth.options.users = [];
usersauth.loadUsers();
```

I understand that this way of doing it is dependant on the way the logic is implemented in the module and not using any documented API, but it's a risk I'm willing to take, because I don't think this module will change drastically in the next years.

=)

**Comment by gevorg** [comment]
Yep, that looks like it ;)
